
import React, { useMemo, useState } from "react";
import EmployeeLayout from "../../layouts/EmployeeLayout";
import { useAuth } from "../../context/AuthContext";
import {
  FiAlertCircle,
  FiBell,
  FiCalendar,
  FiChevronDown,
  FiClock,
  FiInfo,
  FiSearch,
  FiShield,
  FiUser,
} from "react-icons/fi";
import "./EmployeeAnnouncements.css";

/*
 * Static notices shown by default.
 * Dynamic notices from HR / Manager / System are merged below
 * when AuthContext provides an announcements array.
 */
const STATIC_ANNOUNCEMENTS = [
  {
    id: "static-holiday",
    title: "September Holiday Schedule",
    category: "HR",
    date: "Sep 1",
    content:
      "Please note the upcoming holidays in September. Ganesh Chaturthi on Sep 7 is a mandatory holiday.",
    important: false,
    source: "HR",
    priority: "Normal",
  },
  {
    id: "static-wfh",
    title: "New Work From Home Policy",
    category: "Policy",
    date: "Aug 30",
    content:
      "The company has updated its WFH policy. Employees can now work from home up to 3 days per week with manager approval.",
    important: false,
    source: "HR",
    priority: "Normal",
  },
  {
    id: "static-payroll",
    title: "Payroll Processed — August 2026",
    category: "Payroll",
    date: "Aug 31",
    content:
      "August 2026 payroll has been processed. Salaries will be credited to your bank accounts within 2 working days.",
    important: false,
    source: "System",
    priority: "Normal",
  },
  {
    id: "static-maintenance",
    title: "System Maintenance Alert",
    category: "System",
    date: "Aug 28",
    content:
      "Scheduled maintenance on Sep 5, 2026 between 2:00 AM – 4:00 AM IST. HRMS will be temporarily unavailable.",
    important: true,
    source: "System",
    priority: "Urgent",
  },
];

const normalizeAnnouncement = (item, index) => {
  const source =
    item.source ||
    item.sender ||
    item.createdBy ||
    (item.category === "System" ? "System" : null) ||
    (item.category === "HR" || item.category === "Policy"
      ? "HR"
      : "Manager");

  return {
    ...item,
    id: item.id || `dynamic-${index}`,
    title: item.title || "Company Announcement",
    category: item.category || "General",
    date: item.date || "Recent",
    content: item.content || item.message || "",
    important: Boolean(item.important),
    source,
    priority:
      item.priority ||
      (item.important ? "Important" : "Normal"),
  };
};

const getSourceIcon = (source) => {
  const normalized = String(source || "").toLowerCase();

  if (normalized.includes("system")) {
    return <FiShield />;
  }

  if (normalized.includes("manager")) {
    return <FiUser />;
  }

  if (normalized.includes("hr")) {
    return <FiBell />;
  }

  return <FiInfo />;
};

const getAnnouncementClass = (item) => {
  if (item.important || item.priority === "Urgent") {
    return "emp-announcement-card-urgent";
  }

  const source = String(item.source || "").toLowerCase();

  if (source.includes("system")) {
    return "emp-announcement-card-system";
  }

  if (source.includes("manager")) {
    return "emp-announcement-card-manager";
  }

  return "emp-announcement-card-standard";
};

export default function EmployeeAnnouncements() {
  const { announcements = [] } = useAuth();

  const [searchTerm, setSearchTerm] = useState("");
  const [selectedFilter, setSelectedFilter] = useState("All");
  const [expandedId, setExpandedId] = useState(null);

  /*
   * Keep the four supplied notices visible and merge in
   * announcements generated by HR, managers, or the system.
   *
   * If AuthContext already contains one of the static notices,
   * it is not duplicated based on title.
   */
  const allAnnouncements = useMemo(() => {
    const dynamicItems = announcements.map(
      normalizeAnnouncement
    );

    const dynamicTitles = new Set(
      dynamicItems.map((item) =>
        String(item.title).trim().toLowerCase()
      )
    );

    const staticItems = STATIC_ANNOUNCEMENTS.filter(
      (item) =>
        !dynamicTitles.has(
          String(item.title).trim().toLowerCase()
        )
    );

    return [...dynamicItems, ...staticItems];
  }, [announcements]);

  const filterOptions = useMemo(() => {
    const categories = allAnnouncements
      .map((item) => item.category)
      .filter(Boolean);

    return ["All", ...new Set(categories)];
  }, [allAnnouncements]);

  const filteredAnnouncements = useMemo(() => {
    const query = searchTerm.trim().toLowerCase();

    return allAnnouncements.filter((item) => {
      const matchesSearch =
        !query ||
        String(item.title)
          .toLowerCase()
          .includes(query) ||
        String(item.content)
          .toLowerCase()
          .includes(query) ||
        String(item.category)
          .toLowerCase()
          .includes(query) ||
        String(item.source)
          .toLowerCase()
          .includes(query);

      const matchesFilter =
        selectedFilter === "All" ||
        item.category === selectedFilter;

      return matchesSearch && matchesFilter;
    });
  }, [
    allAnnouncements,
    searchTerm,
    selectedFilter,
  ]);

  const importantCount = allAnnouncements.filter(
    (item) => item.important || item.priority === "Urgent"
  ).length;

  const handleCardClick = (id) => {
    setExpandedId((current) =>
      current === id ? null : id
    );
  };

  return (
    <EmployeeLayout
      title="Announcements"
      breadcrumb="Announcements"
    >
      <div className="emp-announcement-page">

        {/* =====================================================
            PAGE HEADER
           ===================================================== */}
        <section className="emp-announcement-header">

          <div className="emp-announcement-header-copy">
            <span className="emp-announcement-eyebrow">
              BELNOVA HRMS
            </span>

            <h1>Announcements</h1>

            <p>
              Stay informed about company updates,
              policies, events, and important HR notices.
            </p>
          </div>

          <div className="emp-announcement-header-badge">
            <div className="emp-announcement-header-badge-icon">
              <FiBell />
            </div>

            <div>
              <strong>
                {allAnnouncements.length}
              </strong>

              <span>Notices</span>
            </div>
          </div>

        </section>


        {/* =====================================================
            OVERVIEW STRIP
           ===================================================== */}
        <section className="emp-announcement-overview">

          <div className="emp-announcement-overview-item">
            <div className="emp-announcement-overview-icon emp-announcement-overview-blue">
              <FiBell />
            </div>

            <div>
              <span>All Notices</span>
              <strong>
                {allAnnouncements.length}
              </strong>
            </div>
          </div>

          <div className="emp-announcement-overview-item">
            <div className="emp-announcement-overview-icon emp-announcement-overview-red">
              <FiAlertCircle />
            </div>

            <div>
              <span>Important</span>
              <strong>{importantCount}</strong>
            </div>
          </div>

          <div className="emp-announcement-overview-item">
            <div className="emp-announcement-overview-icon emp-announcement-overview-green">
              <FiUser />
            </div>

            <div>
              <span>HR / Manager</span>
              <strong>
                {Math.max(
                  allAnnouncements.length -
                    allAnnouncements.filter(
                      (item) =>
                        String(item.source)
                          .toLowerCase()
                          .includes("system")
                    ).length,
                  0
                )}
              </strong>
            </div>
          </div>

          <div className="emp-announcement-overview-item">
            <div className="emp-announcement-overview-icon emp-announcement-overview-purple">
              <FiClock />
            </div>

            <div>
              <span>System Updates</span>
              <strong>
                {
                  allAnnouncements.filter(
                    (item) =>
                      String(item.source)
                        .toLowerCase()
                        .includes("system")
                  ).length
                }
              </strong>
            </div>
          </div>

        </section>


        {/* =====================================================
            FEATURED NOTICE
           ===================================================== */}
        {importantCount > 0 && (
          <section className="emp-announcement-featured">

            <div className="emp-announcement-featured-icon">
              <FiAlertCircle />
            </div>

            <div className="emp-announcement-featured-content">
              <span>IMPORTANT NOTICE</span>

              <h2>
                {
                  allAnnouncements.find(
                    (item) =>
                      item.important ||
                      item.priority === "Urgent"
                  )?.title
                }
              </h2>

              <p>
                {
                  allAnnouncements.find(
                    (item) =>
                      item.important ||
                      item.priority === "Urgent"
                  )?.content
                }
              </p>
            </div>

            <div className="emp-announcement-featured-mark">
              <FiAlertCircle />
            </div>

          </section>
        )}


        {/* =====================================================
            SEARCH / FILTER
           ===================================================== */}
        <section className="emp-announcement-toolbar">

          <div className="emp-announcement-toolbar-title">
            <span>COMPANY UPDATES</span>
            <h2>Latest Announcements</h2>
          </div>

          <div className="emp-announcement-controls">

            <div className="emp-announcement-search">
              <FiSearch />

              <input
                type="search"
                value={searchTerm}
                onChange={(event) =>
                  setSearchTerm(event.target.value)
                }
                placeholder="Search announcements..."
              />
            </div>

            <div className="emp-announcement-filter">
              <select
                value={selectedFilter}
                onChange={(event) =>
                  setSelectedFilter(event.target.value)
                }
              >
                {filterOptions.map((option) => (
                  <option
                    key={option}
                    value={option}
                  >
                    {option === "All"
                      ? "All Categories"
                      : option}
                  </option>
                ))}
              </select>

              <FiChevronDown />
            </div>

          </div>

        </section>


        {/* =====================================================
            ANNOUNCEMENT LIST
           ===================================================== */}
        <section className="emp-announcement-list">

          {filteredAnnouncements.length > 0 ? (
            filteredAnnouncements.map((item) => {
              const isExpanded =
                expandedId === item.id;

              return (
                <article
                  key={item.id}
                  className={`emp-announcement-card ${getAnnouncementClass(
                    item
                  )} ${
                    isExpanded
                      ? "emp-announcement-card-expanded"
                      : ""
                  }`}
                  onClick={() =>
                    handleCardClick(item.id)
                  }
                >

                  <div className="emp-announcement-card-accent" />

                  <div className="emp-announcement-card-icon">
                    {getSourceIcon(item.source)}
                  </div>

                  <div className="emp-announcement-card-main">

                    <div className="emp-announcement-card-top">

                      <div className="emp-announcement-card-meta">

                        <span className="emp-announcement-category">
                          {item.category}
                        </span>

                        <span className="emp-announcement-date">
                          <FiCalendar />
                          {item.date}
                        </span>

                        <span className="emp-announcement-source">
                          {getSourceIcon(item.source)}
                          {item.source || "HR"}
                        </span>

                        {(item.important ||
                          item.priority ===
                            "Urgent") && (
                          <span className="emp-announcement-urgent">
                            <FiAlertCircle />
                            Urgent
                          </span>
                        )}

                      </div>

                      <span className="emp-announcement-chevron">
                        <FiChevronDown />
                      </span>

                    </div>


                    <h3>{item.title}</h3>

                    <p
                      className={
                        isExpanded
                          ? "emp-announcement-content-expanded"
                          : ""
                      }
                    >
                      {item.content}
                    </p>

                    <div className="emp-announcement-card-footer">

                      <span>
                        {isExpanded
                          ? "Click to collapse"
                          : "Click to read full notice"}
                      </span>

                      <span className="emp-announcement-footer-source">
                        {getSourceIcon(item.source)}
                        Published by{" "}
                        {item.source || "HR"}
                      </span>

                    </div>

                  </div>

                </article>
              );
            })
          ) : (
            <div className="emp-announcement-empty">

              <div className="emp-announcement-empty-icon">
                <FiSearch />
              </div>

              <h3>No announcements found</h3>

              <p>
                Try changing your search or category
                filter.
              </p>

              <button
                type="button"
                onClick={() => {
                  setSearchTerm("");
                  setSelectedFilter("All");
                }}
              >
                Clear Filters
              </button>

            </div>
          )}

        </section>


        {/* =====================================================
            INFORMATION FOOTER
           ===================================================== */}
        <section className="emp-announcement-info">

          <div className="emp-announcement-info-icon">
            <FiInfo />
          </div>

          <div>
            <strong>
              Stay up to date
            </strong>

            <span>
              Announcements published by HR, managers,
              and the HRMS system will appear here
              automatically.
            </span>
          </div>

        </section>

      </div>
    </EmployeeLayout>
  );
}
